### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Celtir** [finn-no/unleash#152]
Hei. I would really like to use unleash in trainingportal.no systems, but in order to do so I need to be sure that project will be supported (and actively develop )for at least 2 years. Do you have any project roadmap that I could present to management ?

**Comment by sveisvei** [comment]
We do plan to keep this going for quite a while, @ivarconr might fill you further in here.
Currently our roadmap are being work on here: https://github.com/finn-no/unleash/wiki/Roadmap

**Comment by ivarconr** [comment]
Happy to hear you are considering unleash. =)

We do not have two-years roadmaps, but we could (and probably should) add some thoughts for the next versions. 

The short-term goal is to come with a 'easy-to-adopt' version of unleash, which shall be less FINN-specific, and make it easier for other companies to adopt it. We have also decided to include aggregate strategies in the first version as this requires us to do some API-changes (something we have never done before) and is probably the most missed feature. The ETA for Unleash version 1.0 is mid October. 

Unleash is already, and will continue to be a crucial part of FINN.no's stack to enable continuous integration of new features. Thus i am confident that it will be maintained, just because we need it our-self. Currently we are two core maintainers (@ivarconr and @sveisvei) and we do accept PR from the community.

**Comment by sveisvei** [comment]
@Celtir we updated the roadmap with features we have in the pipeline.

**Comment by Celtir** [comment]
Hei.

Thank you for quick response. I will check it out.

**Comment by ivarconr** [comment]
@Celtir just out of curiosity, did you end up using Unleash? 
If not, why?
