### ISSUE TITLE
Admin: improve audit-log

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#63]
Should only show the diff of what actually changed, not the full new state.

**Comment by jarib** [comment]
I've started working on this in the [eventDiffer](https://github.com/finn-no/unleash/compare/eventDiffer) branch.

**Comment by ivarconr** [comment]
:+1:

**Comment by jarib** [comment]
Here's my attempt at showing diffs in the UI. It is quite compact but a JSON string diff (perhaps using [jsdiff](https://github.com/kpdecker/jsdiff)) may be easier to read. Another option to improve readability could be to align keys vs values. What do you think?

![image](https://cloud.githubusercontent.com/assets/572/5920268/b818a256-a63b-11e4-91c9-8ff02dafdbf6.png)

A few other things I noticed: 

a) The `feature-archive` and `feature-revive` events seems to not have the complete feature in the event data. This makes for some confusing diffs, e.g.: 

![image](https://cloud.githubusercontent.com/assets/572/5920363/5fc81360-a63c-11e4-85d3-00c12b1a9b46.png)


b) The log page will grow indefinitely and eventually building the diffs in memory will get too expensive. We can solve it through pagination but the diff calculation needs to be aware of the tail being cut off. Otherwise it will show an incorrect/empty diff for the last event in the paginated list.

**Comment by ivarconr** [comment]
As a first attempt this looks awesome! 

A few comments:
- I would like to also be able to see the full JSON-change, maybe via a toggle button or something (because it can be a lot of changes to parse in your head to see the current state after each change)
- We could have the full content for the feature-archive and feature-revive events, but then we probably should extend the model with a field for "archived" or else the diff would empty. (or maybe that's the point?). Another point might be that archiving and revving toggles probably do not need diffs as they are self-descriptive and should not change the content of a toggle.
- I am not to worried about the logs growing indefinitely. How could we add pagination and making the diffing aware of it without to much complexity?

**Comment by jarib** [comment]
@ivarconr Do you want a toggle to (a) see a JSON string diff, or (b) the full event data object?

**Comment by ivarconr** [comment]
I was thinking the full event data object. What do you think?

**Comment by jarib** [comment]
I agree, seems redundant to have two types of diffs.

**Comment by jarib** [comment]
I've added the toggle and pushed this to master. Further suggestions should be in a new issue :)
